export { default as Header } from './Header';
export { default as HeaderAbout } from './HeaderAbout';
export { default as About } from './About';
export { default as OurSolutions } from './OurSolutions';
export { default as OurValues } from './OurValues';
export { default as WhyChooseUs } from './WhyChooseUs';
export { default as Testimonials } from './Testimonials';
export { default as Blogs } from './Blogs';
export { default as Contact } from './Contact';
